# Builder
FROM openjdk:11-jdk-slim as builder

WORKDIR /app
COPY . .

ARG PROJECT_NAME
ARG PROJECT_VERSION
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRINGBOOT_JWT_SECRET
ARG CLOUD_AWS_CREDENTIALS_ACCESSKEY
ARG CLOUD_AWS_CREDENTIALS_SECRETKEY
ARG TEST

ENV PROJECT_NAME=${PROJECT_NAME}
ENV PROJECT_VERSION=${PROJECT_VERSION}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRINGBOOT_JWT_SECRET=${SPRINGBOOT_JWT_SECRET}
ENV CLOUD_AWS_CREDENTIALS_ACCESSKEY=${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
ENV CLOUD_AWS_CREDENTIALS_SECRETKEY=${CLOUD_AWS_CREDENTIALS_SECRETKEY}
ENV TEST=${TEST}

RUN chmod +x gradlew

RUN if [ "$TEST" = "true" ] ; then ./gradlew clean build; \
    else ./gradlew clean build -x test; fi

RUN mv build/libs/${PROJECT_NAME}-${PROJECT_VERSION}.jar app.jar

# Runner
FROM openjdk:11-jre-slim as runner

ARG HJFUND_DEPLOY_TYPE
ENV HJFUND_DEPLOY_TYPE=${HJFUND_DEPLOY_TYPE}

WORKDIR /app
COPY --from=builder /app/app.jar .

CMD ["java", "-jar", "app.jar"]
